### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pulichandramoulireddy** [htafer/remoVecSec#1]
Hi,
This is a nice tool for contamination removal before submission to NCBI. However I am unable to run it successfully and following errors are displayed. Can you help with this error. Thank you. 
python3 ./remower.py --genomefile ../../KB_001.fa -c ../../contam_db/contam_in_euks > ../../test_out                    [12:10PM]
Traceback (most recent call last):
  File "./remower.py", line 67, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./remower.py", line 54, in main
    f = rV.runVecSecPipe(args.genomefile, args.dbvec)
  File "/usr/local/lib/python3.6/dist-packages/remoVecSec-0.0.2-py3.6.egg/remoVecSec/removeVec.py", line 31, in runVecSecPipe
TypeError: must be str, not NoneType

**Comment by antonkulaga** [comment]
Same for me :(
